const Engine = {
    state: {
        gender: 'M',
        totalIntake: 0,

        db: [
            { name: "Chicken Breast (Grilled)", kcal: 165, type: "Protein" },
            {name: "Chicken Thigh (Skinless)", kcal: 209, type: "Protein" },
            { name: "Turkey Breast", kcal: 135, type: "Protein" },
            { name: "Turkey Thigh", kcal: 158, type: "Protein" },
            { name: "Beef Steak (Sirloin)", kcal: 244, type: "Protein" },
            { name: "Ground Beef (90/10)", kcal: 176, type: "Protein" },
            { name: "Pork Tenderloin", kcal: 143, type: "Protein" },
            { name: "Pork Chop (Lean)", kcal: 197, type: "Protein" },
            { name: "Lamb Chop", kcal: 294, type: "Protein" },
            { name: "Venison Steak", kcal: 158, type: "Protein" },
            { name: "Salmon Fillet", kcal: 208, type: "Protein" },
            { name: "Cod Fillet", kcal: 82, type: "Protein" },
            { name: "Tuna (Canned in Water)", kcal: 116, type: "Protein" },
            { name: "Shrimp (Cooked)", kcal: 99, type: "Protein" },
            { name: "Tilapia Fillet", kcal: 96, type: "Protein" },
            { name: "Mackerel", kcal: 205, type: "Protein" },
            { name: "Sardines (Canned in Water)", kcal: 208, type: "Protein" },
            { name: "Egg (Whole)", kcal: 155, type: "Protein" },
            { name: "Egg Whites", kcal: 52, type: "Protein" },
            { name: "Tofu (Firm)", kcal: 83, type: "Protein" },
            { name: "Tempeh", kcal: 193, type: "Protein" },
            { name: "Seitan", kcal: 370, type: "Protein" },
            { name: "Greek Yogurt (Non-fat)", kcal: 59, type: "Protein" },
            { name: "Cottage Cheese (2%)", kcal: 81, type: "Protein" },
            { name: "Mozzarella (Part-Skim)", kcal: 254, type: "Protein" },
            { name: "Feta Cheese", kcal: 264, type: "Protein" },
            { name: "Whey Protein Powder", kcal: 350, type: "Protein" },
            { name: "Casein Protein Powder", kcal: 360, type: "Protein" },
            { name: "Pea Protein Powder", kcal: 400, type: "Protein" },
            { name: "Soy Protein Isolate", kcal: 338, type: "Protein" },
            { name: "Paneer Cheese", kcal: 321, type: "Protein" },
            { name: "Almonds", kcal: 579, type: "Protein" },
            { name: "Peanuts", kcal: 567, type: "Protein" },
            { name: "Walnuts", kcal: 654, type: "Protein" },
            { name: "Pumpkin Seeds", kcal: 559, type: "Protein" },
            { name: "Chia Seeds", kcal: 486, type: "Protein" },
            { name: "Edamame", kcal: 121, type: "Protein" },
            { name: "Black Beans (Boiled)", kcal: 132, type: "Protein" },
            { name: "Lentils (Boiled)", kcal: 116, type: "Protein" },
            { name: "Chickpeas (Boiled)", kcal: 164, type: "Protein" },
            { name: "Quinoa", kcal: 120, type: "Protein" },
            { name: "Buckwheat (Cooked)", kcal: 92, type: "Protein" },
            { name: "Amaranth (Cooked)", kcal: 102, type: "Protein" },
            { name: "Bone Broth", kcal: 40, type: "Protein" },
            { name: "Skyr Yogurt", kcal: 63, type: "Protein" },


            { name: "White Rice (Cooked)", kcal: 130, type: "Carb" },
            { name: "Brown Rice (Cooked)", kcal: 111, type: "Carb" },
            { name: "Quinoa (Cooked)", kcal: 120, type: "Carb" },
            { name: "Oatmeal (Cooked)", kcal: 71, type: "Carb" },
            { name: "Pasta (Cooked)", kcal: 131, type: "Carb" },
            { name: "Sweet Potato (Baked)", kcal: 90, type: "Carb" },
            { name: "Potato (Boiled)", kcal: 77, type: "Carb" },
            { name: "Whole Wheat Bread", kcal: 247, type: "Carb" },
            { name: "Sourdough Bread", kcal: 289, type: "Carb" },
            { name: "Bagel (Plain)", kcal: 250, type: "Carb" },
            { name: "Corn Tortilla", kcal: 218, type: "Carb" },
            { name: "Bulgur (Cooked)", kcal: 83, type: "Carb" },
            { name: "Barley (Cooked)", kcal: 123, type: "Carb" },
            { name: "Millet (Cooked)", kcal: 119, type: "Carb" },
            { name: "Chickpeas (Boiled)", kcal: 164, type: "Carb" },
            { name: "Black Beans (Boiled)", kcal: 132, type: "Carb" },
            { name: "Banana", kcal: 89, type: "Carb" },
            { name: "Apple", kcal: 52, type: "Carb" },
            { name: "Blueberries", kcal: 57, type: "Carb" },
            { name: "Strawberries", kcal: 32, type: "Carb" },
            { name: "Mango", kcal: 60, type: "Carb" },
            { name: "Pineapple", kcal: 50, type: "Carb" },
            { name: "Orange", kcal: 47, type: "Carb" },
            { name: "Watermelon", kcal: 30, type: "Carb" },
            { name: "Kiwi", kcal: 61, type: "Carb" },
            { name: "Raisins", kcal: 299, type: "Carb" },
            { name: "Dates (Medjool)", kcal: 277, type: "Carb" },
            { name: "Honey", kcal: 304, type: "Carb" },
            { name: "Maple Syrup", kcal: 260, type: "Carb" },
            { name: "Cornflakes", kcal: 357, type: "Carb" },
            { name: "Granola", kcal: 471, type: "Carb" },
            { name: "Rice Cakes", kcal: 387, type: "Carb" },
            { name: "Pretzels", kcal: 380, type: "Carb" },
            { name: "Pita Bread", kcal: 275, type: "Carb" },
            { name: "Croissant", kcal: 406, type: "Carb" },
            { name: "Spaghetti", kcal: 158, type: "Carb" },
            { name: "Ramen Noodles", kcal: 436, type: "Carb" },
            { name: "Rolled Oats", kcal: 389, type: "Carb" },

        
                                        
            { name: "Avocado", kcal: 160, type: "Fat" },
            { name: "Olive Oil", kcal: 884, type: "Fat" },
            { name: "Coconut Oil", kcal: 862, type: "Fat" },
            { name: "Butter", kcal: 717, type: "Fat" },
            { name: "Mayonnaise", kcal: 680, type: "Fat" },
            { name: "Ranch Dressing", kcal: 430, type: "Fat" },
            { name: "Caesar Dressing", kcal: 470, type: "Fat" },
            { name: "Heavy Cream", kcal: 340, type: "Fat" },
            { name: "Cream Cheese", kcal: 342, type: "Fat" },
            { name: "Sour Cream", kcal: 193, type: "Fat" },
            { name: "Cheddar Cheese", kcal: 402, type: "Fat" },
            { name: "Parmesan", kcal: 431, type: "Fat" },
            { name: "Mozzarella", kcal: 280, type: "Fat" },
            { name: "Feta", kcal: 264, type: "Fat" },
            { name: "Almonds", kcal: 579, type: "Fat" },
            { name: "Walnuts", kcal: 654, type: "Fat" },
            { name: "Pistachios", kcal: 562, type: "Fat" },
            { name: "Peanuts", kcal: 567, type: "Fat" },
            { name: "Hazelnuts", kcal: 628, type: "Fat" },
            { name: "Sunflower Seeds", kcal: 584, type: "Fat" },
            { name: "Dark Chocolate", kcal: 546, type: "Fat" },
            { name: "Olives", kcal: 145, type: "Fat" },
            { name: "Ice Cream", kcal: 207, type: "Fat" },
            { name: "Hamburger", kcal: 250, type: "Fat" },
            { name: "French Fries", kcal: 312, type: "Fat" },
            { name: "Fried Chicken", kcal: 320, type: "Fat" },
            { name: "Cheese Pizza", kcal: 250, type: "Fat" },
            { name: "Hot Dog", kcal: 290, type: "Fat" },
            { name: "Onion Rings", kcal: 276, type: "Fat" },
            { name: "Macadamia Nuts", kcal: 718, type: "Fat" },
            { name: "Brazil Nuts", kcal: 656, type: "Fat" },
            { name: "Cashews", kcal: 553, type: "Fat" },
            { name: "Pecans", kcal: 691, type: "Fat" },
            { name: "Ghee", kcal: 900, type: "Fat" },
            { name: "Tahini", kcal: 595, type: "Fat" },
            { name: "Peanut Oil", kcal: 884, type: "Fat" },
            { name: "Sunflower Oil", kcal: 884, type: "Fat" },
            { name: "Avocado Oil", kcal: 884, type: "Fat" },
            { name: "Sesame Oil", kcal: 884, type: "Fat" },
            { name: "Pecan Butter", kcal: 691, type: "Fat" },
            { name: "Almond Butter", kcal: 614, type: "Fat" },
            { name: "Coconut Butter", kcal: 892, type: "Fat" },
            { name: "Cheese Slice", kcal: 113, type: "Fat" },
            { name: "Cream", kcal: 340, type: "Fat" },
            { name: "Blue Cheese", kcal: 353, type: "Fat" },
            { name: "Brie", kcal: 334, type: "Fat" },
            { name: "Camembert", kcal: 300, type: "Fat" },
            { name: "Halloumi", kcal: 321, type: "Fat" },


            { name: "Broccoli", kcal: 34, type: "Fiber" },
            { name: "Spinach", kcal: 23, type: "Fiber" },
            { name: "Kale", kcal: 49, type: "Fiber" },
            { name: "Asparagus", kcal: 20, type: "Fiber" },
            { name: "Zucchini", kcal: 17, type: "Fiber" },
            { name: "Cauliflower", kcal: 25, type: "Fiber" },
            { name: "Carrots", kcal: 41, type: "Fiber" },
            { name: "Bell Pepper", kcal: 31, type: "Fiber" },
            { name: "Cucumber", kcal: 15, type: "Fiber" },
            { name: "Green Beans", kcal: 31, type: "Fiber" },
            { name: "Brussels Sprouts", kcal: 43, type: "Fiber" },
            { name: "Cabbage", kcal: 25, type: "Fiber" },
            { name: "Celery", kcal: 16, type: "Fiber" },
            { name: "Eggplant", kcal: 25, type: "Fiber" },
            { name: "Onion", kcal: 40, type: "Fiber" },
            { name: "Pumpkin", kcal: 26, type: "Fiber" },
            { name: "Leek", kcal: 61, type: "Fiber" },
            { name: "Bok Choy", kcal: 13, type: "Fiber" },
            { name: "Swiss Chard", kcal: 19, type: "Fiber" },
            { name: "Turnip", kcal: 28, type: "Fiber" },
            { name: "Arugula", kcal: 25, type: "Fiber" },
            { name: "Mustard Greens", kcal: 27, type: "Fiber" },
            { name: "Okra", kcal: 33, type: "Fiber" },
            { name: "Seaweed", kcal: 45, type: "Fiber" },
            { name: "Collard Greens", kcal: 32, type: "Fiber" },
            { name: "Rutabaga", kcal: 38, type: "Fiber" },
            { name: "Tomato", kcal: 18, type: "Fiber" },
            { name: "Sweet Corn", kcal: 96, type: "Fiber" },
            { name: "Artichoke", kcal: 47, type: "Fiber" },
            { name: "Chayote", kcal: 19, type: "Fiber" },
            { name: "Portobello Mushroom", kcal: 29, type: "Fiber" },
            { name: "Shiitake Mushroom", kcal: 34, type: "Fiber" },
            { name: "Enoki Mushroom", kcal: 37, type: "Fiber" },



            { name: "Pizza (Pepperoni)", kcal: 266, type: "Cheat" },
            { name: "Burger (Fast Food)", kcal: 295, type: "Cheat" },
            { name: "French Fries", kcal: 312, type: "Cheat" },
            { name: "Dark Chocolate (85%)", kcal: 598, type: "Cheat" },
            { name: "Ice Cream (Vanilla)", kcal: 207, type: "Cheat" },
            { name: "Donut (Glazed)", kcal: 452, type: "Cheat" },
            { name: "Potato Chips", kcal: 536, type: "Cheat" },
            { name: "Chocolate Chip Cookie", kcal: 492, type: "Cheat" },
            { name: "Brownie", kcal: 466, type: "Cheat" },
            { name: "Cupcake (Frosted)", kcal: 377, type: "Cheat" },
            { name: "Blueberry Muffin", kcal: 375, type: "Cheat" },
            { name: "Croissant", kcal: 406, type: "Cheat" },
            { name: "Cinnamon Roll", kcal: 400, type: "Cheat" },
            { name: "Apple Pie", kcal: 237, type: "Cheat" },
            { name: "Pecan Pie", kcal: 413, type: "Cheat" },
            { name: "Chocolate Cake", kcal: 371, type: "Cheat" },
            { name: "Cheesecake", kcal: 321, type: "Cheat" },
            { name: "Hot Dog (with bun)", kcal: 290, type: "Cheat" },
            { name: "Corn Dog", kcal: 250, type: "Cheat" },
            { name: "Chicken Nuggets", kcal: 296, type: "Cheat" },
            { name: "Fried Chicken", kcal: 246, type: "Cheat" },
            { name: "Taco", kcal: 226, type: "Cheat" },
            { name: "Burrito", kcal: 190, type: "Cheat" },
            { name: "Nachos", kcal: 306, type: "Cheat" },
            { name: "Mozzarella Sticks", kcal: 318, type: "Cheat" },
            { name: "Onion Rings", kcal: 411, type: "Cheat" },
            { name: "Tater Tots", kcal: 315, type: "Cheat" },
            { name: "Macaroni and Cheese", kcal: 164, type: "Cheat" },
            { name: "Ramen", kcal: 436, type: "Cheat" },
            { name: "Popcorn", kcal: 583, type: "Cheat" },
            { name: "Churro", kcal: 461, type: "Cheat" },
            { name: "Cotton Candy", kcal: 394, type: "Cheat" },
            { name: "Marshmallow", kcal: 318, type: "Cheat" },
            { name: "Gummy Bears", kcal: 343, type: "Cheat" },
            { name: "Jelly Beans", kcal: 375, type: "Cheat" },
            { name: "Milk Chocolate Bar", kcal: 535, type: "Cheat" },
            { name: "Peanut Butter Cups", kcal: 515, type: "Cheat" },
            { name: "Waffle (with syrup)", kcal: 291, type: "Cheat" },
            { name: "Pancakes (with syrup)", kcal: 227, type: "Cheat" },
            { name: "French Toast", kcal: 229, type: "Cheat" },
            { name: "Milkshake (Chocolate)", kcal: 112, type: "Cheat" },
            { name: "Soda (Cola)", kcal: 41, type: "Cheat" },
            { name: "Deep Dish Pizza", kcal: 275, type: "Cheat" },
            { name: "Stuffed Crust Pizza", kcal: 310, type: "Cheat" },
            { name: "Loaded Nachos", kcal: 343, type: "Cheat" },
            { name: "Chili Cheese Fries", kcal: 350, type: "Cheat" },
            { name: "Philly Cheesesteak", kcal: 300, type: "Cheat" },
            { name: "Fried Mozzarella Sandwich", kcal: 410, type: "Cheat" },
            { name: "Loaded Baked Potato", kcal: 278, type: "Cheat" },
            { name: "Fried Shrimp", kcal: 242, type: "Cheat" },
            { name: "Lasagna", kcal: 135, type: "Cheat" },
            { name: "Garlic Bread", kcal: 350, type: "Cheat" },
            { name: "Buffalo Wings", kcal: 290, type: "Cheat" },

            
            { name: "Water", kcal: 0, type: "Drink" },
            { name: "Sparkling Water", kcal: 0, type: "Drink" },
            { name: "Mineral Water", kcal: 0, type: "Drink" },
            { name: "Club Soda", kcal: 0, type: "Drink" },
            { name: "Lemon Water", kcal: 5, type: "Drink" },
            { name: "Iced Tea (Unsweetened)", kcal: 2, type: "Drink" },
            { name: "Sweet Iced Tea", kcal: 35, type: "Drink" },
            { name: "Peach Iced Tea", kcal: 35, type: "Drink" },
            { name: "Raspberry Iced Tea", kcal: 40, type: "Drink" },
            { name: "Black Coffee", kcal: 2, type: "Drink" },
            { name: "Espresso", kcal: 9, type: "Drink" },
            { name: "Americano", kcal: 5, type: "Drink" },
            { name: "Iced Coffee", kcal: 2, type: "Drink" },
            { name: "Cold Brew Coffee", kcal: 5, type: "Drink" },
            { name: "Latte", kcal: 63, type: "Drink" },
            { name: "Cappuccino", kcal: 48, type: "Drink" },
            { name: "Vanilla Latte", kcal: 120, type: "Drink" },
            { name: "Caramel Latte", kcal: 150, type: "Drink" },
            { name: "Pumpkin Spice Latte", kcal: 190, type: "Drink" },
            { name: "Mocha", kcal: 197, type: "Drink" },
            { name: "Hot Chocolate", kcal: 77, type: "Drink" },
            { name: "Green Tea", kcal: 1, type: "Drink" },
            { name: "Matcha Tea", kcal: 3, type: "Drink" },
            { name: "Matcha Latte", kcal: 80, type: "Drink" },
            { name: "Whole Milk", kcal: 61, type: "Drink" },
            { name: "Skim Milk", kcal: 34, type: "Drink" },
            { name: "Almond Milk", kcal: 15, type: "Drink" },
            { name: "Soy Milk", kcal: 54, type: "Drink" },
            { name: "Oat Milk", kcal: 46, type: "Drink" },
            { name: "Orange Juice", kcal: 45, type: "Drink" },
            { name: "Apple Juice", kcal: 46, type: "Drink" },
            { name: "Grape Juice", kcal: 60, type: "Drink" },
            { name: "Cranberry Juice", kcal: 46, type: "Drink" },
            { name: "Watermelon Juice", kcal: 30, type: "Drink" },
            { name: "Lemonade", kcal: 40, type: "Drink" },
            { name: "Lime Soda", kcal: 40, type: "Drink" },
            { name: "Cola", kcal: 41, type: "Drink" },
            { name: "Diet Cola", kcal: 1, type: "Drink" },
            { name: "Cola Zero", kcal: 1, type: "Drink" },
            { name: "Root Beer", kcal: 41, type: "Drink" },
            { name: "Tonic Water", kcal: 34, type: "Drink" },
            { name: "Energy Drink", kcal: 45, type: "Drink" },
            { name: "Banana Smoothie", kcal: 120, type: "Drink" },
            { name: "Strawberry Smoothie", kcal: 110, type: "Drink" },
            { name: "Blueberry Smoothie", kcal: 120, type: "Drink" },
            { name: "Protein Shake", kcal: 150, type: "Drink" },
            { name: "Coconut Water", kcal: 19, type: "Drink" },
            { name: "Chocolate Milk", kcal: 83, type: "Drink" },
            { name: "Strawberry Milk", kcal: 90, type: "Drink" },
            { name: "Bubble Tea (Milk Tea)", kcal: 180, type: "Drink" },



            { name: "Beer", kcal: 43, type: "Alcohol" },
            { name: "Red Wine", kcal: 85, type: "Alcohol" },
            { name: "White Wine", kcal: 82, type: "Alcohol" },
            { name: "Rosé Wine", kcal: 83, type: "Alcohol" },
            { name: "Champagne", kcal: 76, type: "Alcohol" },
            { name: "Whiskey", kcal: 250, type: "Alcohol" },
            { name: "Vodka", kcal: 231, type: "Alcohol" },
            { name: "Rum", kcal: 231, type: "Alcohol" },
            { name: "Gin", kcal: 263, type: "Alcohol" },
            { name: "Tequila", kcal: 231, type: "Alcohol" },
            { name: "Brandy", kcal: 237, type: "Alcohol" },
            { name: "Cider", kcal: 50, type: "Alcohol" },
            { name: "Baileys Irish Cream", kcal: 327, type: "Alcohol" },
            { name: "Sake", kcal: 134, type: "Alcohol" }
        ]
    },

    ui: {

        switchTab: (id, btn) => {
            document.querySelectorAll('.stage').forEach(s => s.classList.remove('active'));
            document.querySelectorAll('.tab').forEach(t => t.classList.remove('active'));
            document.getElementById(`tab-${id}`).classList.add('active');
            btn.classList.add('active');
        },

        setGender: (g, btn) => {
            Engine.state.gender = g;
            document.querySelectorAll('.choice').forEach(c => c.classList.remove('active'));
            btn.classList.add('active');
        },

        updateBars: (p, c, f) => {

            document.getElementById('p-bar').style.width = p + '%';
            document.getElementById('p-val').innerText = p + '%';

            document.getElementById('c-bar').style.width = c + '%';
            document.getElementById('c-val').innerText = c + '%';

            document.getElementById('f-bar').style.width = f + '%';
            document.getElementById('f-val').innerText = f + '%';

        }
    }

};      