const Engine = {
    state: {
        gender: 'M',
        totalIntake: 0,

        db: [
            { name: "Chicken Breast", kcal: 165, type: "Protein" },
            { name: "Turkey Breast", kcal: 135, type: "Protein" },
            { name: "Lean Beef", kcal: 250, type: "Protein" },
            { name: "Ground Beef", kcal: 254, type: "Protein" },
            { name: "Pork Loin", kcal: 242, type: "Protein" },
            { name: "Ham", kcal: 145, type: "Protein" },
            { name: "Bacon", kcal: 541, type: "Protein" },
            { name: "Salami", kcal: 407, type: "Protein" },
            { name: "Pepperoni", kcal: 494, type: "Protein" },
            { name: "Sausage", kcal: 301, type: "Protein" },
            { name: "Salmon", kcal: 208, type: "Protein" },
            { name: "Tuna", kcal: 132, type: "Protein" },
            { name: "Cod", kcal: 82, type: "Protein" },
            { name: "Shrimp", kcal: 99, type: "Protein" },
            { name: "Crab", kcal: 97, type: "Protein" },
            { name: "Lobster", kcal: 89, type: "Protein" },
            { name: "Egg", kcal: 155, type: "Protein" },
            { name: "Egg White", kcal: 52, type: "Protein" },
            { name: "Duck Egg", kcal: 185, type: "Protein" },
            { name: "Greek Yogurt", kcal: 59, type: "Protein" },
            { name: "Cottage Cheese", kcal: 98, type: "Protein" },
            { name: "Milk", kcal: 61, type: "Protein" },
            { name: "Chocolate Milk", kcal: 83, type: "Protein" },
            { name: "Protein Shake", kcal: 150, type: "Protein" },
            { name: "Whey Protein", kcal: 400, type: "Protein" },
            { name: "Casein Protein", kcal: 360, type: "Protein" },
            { name: "Soy Protein", kcal: 360, type: "Protein" },
            { name: "Tofu", kcal: 76, type: "Protein" },
            { name: "Lentils", kcal: 116, type: "Protein" },
            { name: "Chickpeas", kcal: 164, type: "Protein" },
            { name: "Black Beans", kcal: 132, type: "Protein" },
            { name: "Kidney Beans", kcal: 127, type: "Protein" },
            { name: "Soybeans", kcal: 173, type: "Protein" },
            { name: "Peanut Butter", kcal: 588, type: "Protein" },

            { name: "White Rice", kcal: 130, type: "Carb" },
            { name: "Brown Rice", kcal: 123, type: "Carb" },
            { name: "Pasta", kcal: 131, type: "Carb" },
            { name: "Spaghetti", kcal: 158, type: "Carb" },
            { name: "Oatmeal", kcal: 68, type: "Carb" },
            { name: "Rolled Oats", kcal: 389, type: "Carb" },
            { name: "Potato", kcal: 77, type: "Carb" },
            { name: "Sweet Potato", kcal: 86, type: "Carb" },
            { name: "Bread", kcal: 265, type: "Carb" },
            { name: "Tortilla", kcal: 237, type: "Carb" },
            { name: "Corn", kcal: 96, type: "Carb" },
            { name: "Banana", kcal: 89, type: "Carb" },
            { name: "Apple", kcal: 52, type: "Carb" },
            { name: "Mango", kcal: 60, type: "Carb" },
            { name: "Pineapple", kcal: 50, type: "Carb" },
            { name: "Watermelon", kcal: 30, type: "Carb" },
            { name: "Blueberries", kcal: 57, type: "Carb" },
            { name: "Strawberries", kcal: 32, type: "Carb" },
            { name: "Raspberries", kcal: 52, type: "Carb" },
            { name: "Honey", kcal: 304, type: "Carb" },

            { name: "Broccoli", kcal: 34, type: "Fiber" },
            { name: "Spinach", kcal: 23, type: "Fiber" },
            { name: "Kale", kcal: 49, type: "Fiber" },
            { name: "Asparagus", kcal: 20, type: "Fiber" },
            { name: "Zucchini", kcal: 17, type: "Fiber" },
            { name: "Cauliflower", kcal: 25, type: "Fiber" },
            { name: "Carrots", kcal: 41, type: "Fiber" },
            { name: "Bell Pepper", kcal: 31, type: "Fiber" },
            { name: "Mushrooms", kcal: 22, type: "Fiber" },
            { name: "Cucumber", kcal: 15, type: "Fiber" },
            { name: "Green Beans", kcal: 31, type: "Fiber" },
            { name: "Brussels Sprouts", kcal: 43, type: "Fiber" },
            { name: "Cabbage", kcal: 25, type: "Fiber" },
            { name: "Celery", kcal: 16, type: "Fiber" },
            { name: "Radish", kcal: 16, type: "Fiber" },
            { name: "Eggplant", kcal: 25, type: "Fiber" },
            { name: "Onion", kcal: 40, type: "Fiber" },
            { name: "Pumpkin", kcal: 26, type: "Fiber" },
            { name: "Black Beans", kcal: 132, type: "Fiber" },

            { name: "Avocado", kcal: 160, type: "Fat" },
            { name: "Olive Oil", kcal: 884, type: "Fat" },
            { name: "Coconut Oil", kcal: 862, type: "Fat" },
            { name: "Butter", kcal: 717, type: "Fat" },
            { name: "Mayonnaise", kcal: 680, type: "Fat" },
            { name: "Ranch Dressing", kcal: 430, type: "Fat" },
            { name: "Caesar Dressing", kcal: 470, type: "Fat" },
            { name: "Heavy Cream", kcal: 340, type: "Fat" },
            { name: "Cream Cheese", kcal: 342, type: "Fat" },
            { name: "Sour Cream", kcal: 193, type: "Fat" },
            { name: "Cheddar Cheese", kcal: 402, type: "Fat" },
            { name: "Parmesan", kcal: 431, type: "Fat" },
            { name: "Mozzarella", kcal: 280, type: "Fat" },
            { name: "Feta", kcal: 264, type: "Fat" },
            { name: "Almonds", kcal: 579, type: "Fat" },
            { name: "Walnuts", kcal: 654, type: "Fat" },
            { name: "Pistachios", kcal: 562, type: "Fat" },
            { name: "Peanuts", kcal: 567, type: "Fat" },
            { name: "Hazelnuts", kcal: 628, type: "Fat" },
            { name: "Sunflower Seeds", kcal: 584, type: "Fat" },
            { name: "Peanut Butter", kcal: 588, type: "Fat" },
            { name: "Dark Chocolate", kcal: 546, type: "Fat" },
            { name: "Milk Chocolate", kcal: 535, type: "Fat" },
            { name: "Olives", kcal: 145, type: "Fat" },
            { name: "Bacon", kcal: 541, type: "Fat" },
            { name: "Salami", kcal: 407, type: "Fat" },
            { name: "Pepperoni", kcal: 494, type: "Fat" },
            { name: "Sausage", kcal: 301, type: "Fat" },
            { name: "Ice Cream", kcal: 207, type: "Fat" },
            { name: "Vanilla Ice Cream", kcal: 207, type: "Fat" },
            { name: "Cheeseburger", kcal: 295, type: "Fat" },
            { name: "Hamburger", kcal: 250, type: "Fat" },
            { name: "French Fries", kcal: 312, type: "Fat" },,
            { name: "Fried Chicken", kcal: 320, type: "Fat" },
            { name: "Chicken Nuggets", kcal: 296, type: "Fat" },
            { name: "Pepperoni Pizza", kcal: 266, type: "Fat" },
            { name: "Cheese Pizza", kcal: 250, type: "Fat" },
            { name: "Hot Dog", kcal: 290, type: "Fat" },
            { name: "Onion Rings", kcal: 276, type: "Fat" },

            { name: "Water", kcal: 0, type: "Drink" },
            { name: "Sparkling Water", kcal: 0, type: "Drink" },
            { name: "Mineral Water", kcal: 0, type: "Drink" },
            { name: "Lemon Water", kcal: 5, type: "Drink" },
            { name: "Lime Water", kcal: 5, type: "Drink" },
            { name: "Black Coffee", kcal: 2, type: "Drink" },
            { name: "Espresso", kcal: 9, type: "Drink" },
            { name: "Americano", kcal: 5, type: "Drink" },
            { name: "Latte", kcal: 63, type: "Drink" },
            { name: "Cappuccino", kcal: 48, type: "Drink" },
            { name: "Mocha", kcal: 197, type: "Drink" },
            { name: "Iced Coffee", kcal: 2, type: "Drink" },
            { name: "Green Tea", kcal: 1, type: "Drink" },
            { name: "Black Tea", kcal: 2, type: "Drink" },
            { name: "Matcha Tea", kcal: 3, type: "Drink" },
            { name: "Matcha Latte", kcal: 80, type: "Drink" },
            { name: "Iced Tea (Unsweetened)", kcal: 2, type: "Drink" },
            { name: "Sweet Iced Tea", kcal: 35, type: "Drink" },
            { name: "Peach Iced Tea", kcal: 35, type: "Drink" },
            { name: "Raspberry Iced Tea", kcal: 40, type: "Drink" },
            { name: "Hot Chocolate", kcal: 77, type: "Drink" },
            { name: "Chocolate Milk", kcal: 83, type: "Drink" },
            { name: "Milk", kcal: 61, type: "Drink" },
            { name: "Almond Milk", kcal: 15, type: "Drink" },
            { name: "Soy Milk", kcal: 54, type: "Drink" },
            { name: "Oat Milk", kcal: 46, type: "Drink" },
            { name: "Orange Juice", kcal: 45, type: "Drink" },
            { name: "Apple Juice", kcal: 46, type: "Drink" },
            { name: "Banana Smoothie", kcal: 120, type: "Drink" },
            { name: "Strawberry Smoothie", kcal: 110, type: "Drink" },
            { name: "Mango Smoothie", kcal: 135, type: "Drink" },
            { name: "Blueberry Smoothie", kcal: 120, type: "Drink" },
            { name: "Protein Shake", kcal: 150, type: "Drink" },
            { name: "Energy Drink", kcal: 45, type: "Drink" },
            { name: "Coconut Water", kcal: 19, type: "Drink" },
            { name: "Cola", kcal: 41, type: "Drink" },
            { name: "Diet Cola", kcal: 1, type: "Drink" },
            { name: "Cola Zero", kcal: 1, type: "Drink" },
            { name: "Root Beer", kcal: 41, type: "Drink" },
            { name: "Ginger Ale", kcal: 34, type: "Drink" },
            { name: "Tonic Water", kcal: 34, type: "Drink" },
            { name: "Bubble Tea", kcal: 180, type: "Drink" },
            { name: "Milk Tea", kcal: 160, type: "Drink" },


            { name: "Beer", kcal: 43, type: "Alcohol" },
            { name: "Red Wine", kcal: 85, type: "Alcohol" },
            { name: "White Wine", kcal: 82, type: "Alcohol" },
            { name: "Rosé Wine", kcal: 83, type: "Alcohol" },
            { name: "Champagne", kcal: 76, type: "Alcohol" },
            { name: "Whiskey", kcal: 250, type: "Alcohol" },
            { name: "Vodka", kcal: 231, type: "Alcohol" },
            { name: "Rum", kcal: 231, type: "Alcohol" },
            { name: "Gin", kcal: 263, type: "Alcohol" },
            { name: "Tequila", kcal: 231, type: "Alcohol" },
            { name: "Brandy", kcal: 237, type: "Alcohol" },
            { name: "Cider", kcal: 50, type: "Alcohol" },
            { name: "Sake", kcal: 134, type: "Alcohol" }
        ]
    },

    ui: {

        switchTab: (id, btn) => {
            document.querySelectorAll('.stage').forEach(s => s.classList.remove('active'));
            document.querySelectorAll('.tab').forEach(t => t.classList.remove('active'));
            document.getElementById(`tab-${id}`).classList.add('active');
            btn.classList.add('active');
        },

        setGender: (g, btn) => {
            Engine.state.gender = g;
            document.querySelectorAll('.choice').forEach(c => c.classList.remove('active'));
            btn.classList.add('active');
        },

        updateBars: (p, c, f) => {

            document.getElementById('p-bar').style.width = p + '%';
            document.getElementById('p-val').innerText = p + '%';

            document.getElementById('c-bar').style.width = c + '%';
            document.getElementById('c-val').innerText = c + '%';

            document.getElementById('f-bar').style.width = f + '%';
            document.getElementById('f-val').innerText = f + '%';

        }
    }

};