const Engine = {
    state: {
        gender: 'M',
        totalIntake: 0,

        db: [
            { name: "Chicken Breast (Grilled)", kcal: 165, type: "Protein" },
            { name: "Chicken Thigh (Skinless)", kcal: 209, type: "Protein" },
            { name: "Beef Steak (Sirloin)", kcal: 244, type: "Protein" },
            { name: "Beef (Ground 90/10)", kcal: 176, type: "Protein" },
            { name: "Salmon Fillet", kcal: 208, type: "Protein" },
            { name: "Cod Fillet", kcal: 82, type: "Protein" },
            { name: "Tuna (Canned in Water)", kcal: 116, type: "Protein" },
            { name: "Shrimp (Cooked)", kcal: 99, type: "Protein" },
            { name: "Turkey Breast", kcal: 135, type: "Protein" },
            { name: "Pork Tenderloin", kcal: 143, type: "Protein" },
            { name: "Egg (Whole)", kcal: 155, type: "Protein" },
            { name: "Egg Whites", kcal: 52, type: "Protein" },
            { name: "Tofu (Firm)", kcal: 83, type: "Protein" },
            { name: "Tempeh", kcal: 193, type: "Protein" },
            { name: "Greek Yogurt (Non-fat)", kcal: 59, type: "Protein" },
            { name: "Cottage Cheese (2%)", kcal: 81, type: "Protein" },
            { name: "Lamb Chop", kcal: 294, type: "Protein" },
            { name: "Venison Steak", kcal: 158, type: "Protein" },

            { name: "Duck Breast (Skinless)", kcal: 135, type: "Protein" },
            { name: "Turkey Thigh", kcal: 158, type: "Protein" },
            { name: "Bison Steak", kcal: 143, type: "Protein" },
            { name: "Veal Chop", kcal: 206, type: "Protein" },
            { name: "Pork Chop (Lean)", kcal: 197, type: "Protein" },
            { name: "Beef Liver", kcal: 135, type: "Protein" },
            { name: "Chicken Liver", kcal: 119, type: "Protein" },
            { name: "Tilapia Fillet", kcal: 96, type: "Protein" },
            { name: "Mahi-Mahi", kcal: 85, type: "Protein" },
            { name: "Halibut Fillet", kcal: 111, type: "Protein" },
            { name: "Swordfish", kcal: 144, type: "Protein" },
            { name: "Trout (Cooked)", kcal: 190, type: "Protein" },
            { name: "Sardines (Canned in Water)", kcal: 208, type: "Protein" },
            { name: "Mackerel", kcal: 205, type: "Protein" },
            { name: "Crab Meat", kcal: 83, type: "Protein" },
            { name: "Lobster Meat", kcal: 89, type: "Protein" },
            { name: "Scallops", kcal: 69, type: "Protein" },
            { name: "Mussels", kcal: 86, type: "Protein" },
            { name: "Clams", kcal: 74, type: "Protein" },
            { name: "Squid (Calamari, Raw)", kcal: 92, type: "Protein" },
            { name: "Octopus", kcal: 82, type: "Protein" },
            { name: "Edamame", kcal: 121, type: "Protein" },
            { name: "Seitan", kcal: 370, type: "Protein" },
            { name: "Textured Vegetable Protein (TVP)", kcal: 327, type: "Protein" },
            { name: "Whey Protein Powder", kcal: 350, type: "Protein" },
            { name: "Casein Protein Powder", kcal: 360, type: "Protein" },
            { name: "Pea Protein Powder", kcal: 400, type: "Protein" },
            { name: "Soy Protein Isolate", kcal: 338, type: "Protein" },
            { name: "Paneer Cheese", kcal: 321, type: "Protein" },
            { name: "Halloumi Cheese", kcal: 321, type: "Protein" },
            { name: "Ricotta Cheese (Part-Skim)", kcal: 138, type: "Protein" },
            { name: "Mozzarella (Part-Skim)", kcal: 254, type: "Protein" },
            { name: "Prosciutto", kcal: 258, type: "Protein" },
            { name: "Roast Beef (Deli Slice)", kcal: 111, type: "Protein" },
            { name: "Turkey Breast (Deli Slice)", kcal: 104, type: "Protein" },
            { name: "Chicken Breast (Deli Slice)", kcal: 96, type: "Protein" },

            { name: "White Rice (Cooked)", kcal: 130, type: "Carb" },
            { name: "Brown Rice (Cooked)", kcal: 111, type: "Carb" },
            { name: "Quinoa (Cooked)", kcal: 120, type: "Carb" },
            { name: "Oatmeal (Cooked)", kcal: 71, type: "Carb" },
            { name: "Pasta (Wheat, Cooked)", kcal: 131, type: "Carb" },
            { name: "Sweet Potato (Baked)", kcal: 90, type: "Carb" },
            { name: "Potato (Boiled)", kcal: 77, type: "Carb" },
            { name: "Bread (Whole Wheat)", kcal: 247, type: "Carb" },
            { name: "Lentils (Boiled)", kcal: 116, type: "Carb" },
            { name: "Chickpeas (Boiled)", kcal: 164, type: "Carb" },
            { name: "Black Beans (Boiled)", kcal: 132, type: "Carb" },
            { name: "Kidney Beans (Boiled)", kcal: 127, type: "Carb" },
            { name: "Couscous (Cooked)", kcal: 112, type: "Carb" },
            { name: "Rice Cake (Plain)", kcal: 387, type: "Carb" },
            { name: "Corn (Sweet)", kcal: 86, type: "Carb" },
            { name: "Banana", kcal: 89, type: "Carb" },
            { name: "Apple", kcal: 52, type: "Carb" },
            { name: "Blueberries", kcal: 57, type: "Carb" },
            { name: "Strawberries", kcal: 32, type: "Carb" },
            { name: "Mango", kcal: 60, type: "Carb" },
            { name: "Pineapple", kcal: 50, type: "Carb" },
            { name: "Orange", kcal: 47, type: "Carb" },
            { name: "Grapes", kcal: 69, type: "Carb" },
            { name: "Watermelon", kcal: 30, type: "Carb" },
            { name: "Kiwi", kcal: 61, type: "Carb" },

            { name: "Sourdough Bread", kcal: 289, type: "Carb" },
            { name: "Rye Bread", kcal: 259, type: "Carb" },
            { name: "Pita Bread", kcal: 275, type: "Carb" },
            { name: "Naan Bread", kcal: 310, type: "Carb" },
            { name: "Bagel (Plain)", kcal: 250, type: "Carb" },
            { name: "English Muffin", kcal: 227, type: "Carb" },
            { name: "Corn Tortilla", kcal: 218, type: "Carb" },
            { name: "Flour Tortilla", kcal: 297, type: "Carb" },
            { name: "Udon Noodles", kcal: 131, type: "Carb" },
            { name: "Soba Noodles (Cooked)", kcal: 99, type: "Carb" },
            { name: "Rice Noodles (Cooked)", kcal: 109, type: "Carb" },
            { name: "Gnocchi", kcal: 133, type: "Carb" },
            { name: "Barley (Cooked)", kcal: 123, type: "Carb" },
            { name: "Farro (Cooked)", kcal: 170, type: "Carb" },
            { name: "Bulgur (Cooked)", kcal: 83, type: "Carb" },
            { name: "Millet (Cooked)", kcal: 119, type: "Carb" },
            { name: "Buckwheat (Cooked)", kcal: 92, type: "Carb" },
            { name: "Amaranth (Cooked)", kcal: 102, type: "Carb" },
            { name: "Polenta (Cooked)", kcal: 85, type: "Carb" },
            { name: "Plantain (Cooked)", kcal: 116, type: "Carb" },
            { name: "Yam (Cooked)", kcal: 116, type: "Carb" },
            { name: "Taro (Cooked)", kcal: 142, type: "Carb" },
            { name: "Parsnip (Cooked)", kcal: 71, type: "Carb" },
            { name: "Cherry", kcal: 50, type: "Carb" },
            { name: "Plum", kcal: 46, type: "Carb" },
            { name: "Peach", kcal: 39, type: "Carb" },
            { name: "Nectarine", kcal: 44, type: "Carb" },
            { name: "Pear", kcal: 57, type: "Carb" },
            { name: "Pomegranate Seeds", kcal: 83, type: "Carb" },
            { name: "Fig (Fresh)", kcal: 74, type: "Carb" },
            { name: "Dates (Medjool)", kcal: 277, type: "Carb" },
            { name: "Raisins", kcal: 299, type: "Carb" },
            { name: "Cranberries (Dried)", kcal: 308, type: "Carb" },
            { name: "Raspberries", kcal: 52, type: "Carb" },
            { name: "Blackberries", kcal: 43, type: "Carb" },
            { name: "Cantaloupe", kcal: 34, type: "Carb" },
            { name: "Honeydew Melon", kcal: 36, type: "Carb" },
            { name: "Papaya", kcal: 43, type: "Carb" },
            { name: "Passion Fruit", kcal: 97, type: "Carb" },
            { name: "Pinto Beans (Cooked)", kcal: 143, type: "Carb" },
            { name: "Navy Beans (Cooked)", kcal: 140, type: "Carb" },
            { name: "Cannellini Beans (Cooked)", kcal: 139, type: "Carb" },

            { name: "Avocado", kcal: 160, type: "Fat" },
            { name: "Olive Oil", kcal: 884, type: "Fat" },
            { name: "Coconut Oil", kcal: 862, type: "Fat" },
            { name: "Butter (Unsalted)", kcal: 717, type: "Fat" },
            { name: "Peanut Butter", kcal: 588, type: "Fat" },
            { name: "Almonds", kcal: 579, type: "Fat" },
            { name: "Walnuts", kcal: 654, type: "Fat" },
            { name: "Cashews", kcal: 553, type: "Fat" },
            { name: "Chia Seeds", kcal: 486, type: "Fat" },
            { name: "Pumpkin Seeds", kcal: 559, type: "Fat" },
            { name: "Pistachios", kcal: 562, type: "Fat" },
            { name: "Flax Seeds", kcal: 534, type: "Fat" },

            { name: "Macadamia Nuts", kcal: 718, type: "Fat" },
            { name: "Pecans", kcal: 691, type: "Fat" },
            { name: "Brazil Nuts", kcal: 659, type: "Fat" },
            { name: "Pine Nuts", kcal: 673, type: "Fat" },
            { name: "Hazelnuts", kcal: 628, type: "Fat" },
            { name: "Peanuts (Roasted)", kcal: 585, type: "Fat" },
            { name: "Sunflower Seeds", kcal: 584, type: "Fat" },
            { name: "Sesame Seeds", kcal: 573, type: "Fat" },
            { name: "Hemp Seeds", kcal: 553, type: "Fat" },
            { name: "Avocado Oil", kcal: 884, type: "Fat" },
            { name: "Sesame Oil", kcal: 884, type: "Fat" },
            { name: "Peanut Oil", kcal: 884, type: "Fat" },
            { name: "Canola Oil", kcal: 884, type: "Fat" },
            { name: "Grapeseed Oil", kcal: 884, type: "Fat" },
            { name: "Sunflower Oil", kcal: 884, type: "Fat" },
            { name: "Walnut Oil", kcal: 884, type: "Fat" },
            { name: "Macadamia Oil", kcal: 884, type: "Fat" },
            { name: "Ghee", kcal: 899, type: "Fat" },
            { name: "Lard", kcal: 900, type: "Fat" },
            { name: "Beef Tallow", kcal: 902, type: "Fat" },
            { name: "Duck Fat", kcal: 882, type: "Fat" },
            { name: "Heavy Cream", kcal: 340, type: "Fat" },
            { name: "Cream Cheese", kcal: 342, type: "Fat" },
            { name: "Sour Cream (Full Fat)", kcal: 193, type: "Fat" },
            { name: "Mayonnaise", kcal: 680, type: "Fat" },
            { name: "Bacon (Cooked)", kcal: 541, type: "Fat" },
            { name: "Pancetta", kcal: 418, type: "Fat" },
            { name: "Chorizo", kcal: 455, type: "Fat" },
            { name: "Black Olives", kcal: 115, type: "Fat" },
            { name: "Green Olives", kcal: 145, type: "Fat" },
            { name: "Kalamata Olives", kcal: 239, type: "Fat" },
            { name: "Tahini", kcal: 595, type: "Fat" },
            { name: "Almond Butter", kcal: 614, type: "Fat" },
            { name: "Cashew Butter", kcal: 587, type: "Fat" },
            { name: "Sunflower Seed Butter", kcal: 617, type: "Fat" },
            { name: "Macadamia Nut Butter", kcal: 718, type: "Fat" },
            { name: "Cocoa Butter", kcal: 884, type: "Fat" },

            { name: "Broccoli", kcal: 34, type: "Fiber" },
            { name: "Spinach (Raw)", kcal: 23, type: "Fiber" },
            { name: "Kale (Raw)", kcal: 49, type: "Fiber" },
            { name: "Asparagus", kcal: 20, type: "Fiber" },
            { name: "Zucchini", kcal: 17, type: "Fiber" },
            { name: "Cauliflower", kcal: 25, type: "Fiber" },
            { name: "Carrots", kcal: 41, type: "Fiber" },
            { name: "Bell Pepper", kcal: 31, type: "Fiber" },
            { name: "Mushrooms", kcal: 22, type: "Fiber" },
            { name: "Cucumber", kcal: 15, type: "Fiber" },
            { name: "Green Beans", kcal: 31, type: "Fiber" },

            { name: "Brussels Sprouts", kcal: 43, type: "Fiber" },
            { name: "Cabbage (Green)", kcal: 25, type: "Fiber" },
            { name: "Cabbage (Red)", kcal: 31, type: "Fiber" },
            { name: "Bok Choy", kcal: 13, type: "Fiber" },
            { name: "Swiss Chard", kcal: 19, type: "Fiber" },
            { name: "Collard Greens", kcal: 32, type: "Fiber" },
            { name: "Mustard Greens", kcal: 27, type: "Fiber" },
            { name: "Arugula", kcal: 25, type: "Fiber" },
            { name: "Watercress", kcal: 11, type: "Fiber" },
            { name: "Iceberg Lettuce", kcal: 14, type: "Fiber" },
            { name: "Romaine Lettuce", kcal: 17, type: "Fiber" },
            { name: "Celery", kcal: 16, type: "Fiber" },
            { name: "Radish", kcal: 16, type: "Fiber" },
            { name: "Daikon", kcal: 18, type: "Fiber" },
            { name: "Jicama", kcal: 38, type: "Fiber" },
            { name: "Artichoke", kcal: 47, type: "Fiber" },
            { name: "Eggplant", kcal: 25, type: "Fiber" },
            { name: "Okra", kcal: 33, type: "Fiber" },
            { name: "Leek", kcal: 61, type: "Fiber" },
            { name: "Onion (Red)", kcal: 40, type: "Fiber" },
            { name: "Onion (White)", kcal: 40, type: "Fiber" },
            { name: "Scallions (Green Onion)", kcal: 32, type: "Fiber" },
            { name: "Shallot", kcal: 72, type: "Fiber" },
            { name: "Garlic", kcal: 149, type: "Fiber" }, // High kcal but small serving normally
            { name: "Fennel", kcal: 31, type: "Fiber" },
            { name: "Kohlrabi", kcal: 27, type: "Fiber" },
            { name: "Snow Peas", kcal: 42, type: "Fiber" },
            { name: "Snap Peas", kcal: 42, type: "Fiber" },
            { name: "Bean Sprouts", kcal: 30, type: "Fiber" },
            { name: "Alfalfa Sprouts", kcal: 23, type: "Fiber" },
            { name: "Bamboo Shoots", kcal: 27, type: "Fiber" },
            { name: "Water Chestnuts", kcal: 97, type: "Fiber" },
            { name: "Hearts of Palm", kcal: 115, type: "Fiber" },
            { name: "Nopales (Cactus)", kcal: 16, type: "Fiber" },
            { name: "Seaweed (Wakame)", kcal: 45, type: "Fiber" },
            { name: "Squash (Butternut)", kcal: 45, type: "Fiber" },
            { name: "Squash (Spaghetti)", kcal: 31, type: "Fiber" },
            { name: "Pumpkin (Raw)", kcal: 26, type: "Fiber" },

            { name: "Pizza (Pepperoni)", kcal: 266, type: "Cheat" },
            { name: "Burger (Fast Food)", kcal: 295, type: "Cheat" },
            { name: "French Fries", kcal: 312, type: "Cheat" },
            { name: "Dark Chocolate (85%)", kcal: 598, type: "Cheat" },
            { name: "Ice Cream (Vanilla)", kcal: 207, type: "Cheat" },
            { name: "Donut (Glazed)", kcal: 452, type: "Cheat" },
            { name: "Potato Chips", kcal: 536, type: "Cheat" },

            { name: "Chocolate Chip Cookie", kcal: 492, type: "Cheat" },
            { name: "Brownie", kcal: 466, type: "Cheat" },
            { name: "Cupcake (Frosted)", kcal: 377, type: "Cheat" },
            { name: "Blueberry Muffin", kcal: 375, type: "Cheat" },
            { name: "Croissant", kcal: 406, type: "Cheat" },
            { name: "Cinnamon Roll", kcal: 400, type: "Cheat" },
            { name: "Apple Pie", kcal: 237, type: "Cheat" },
            { name: "Pecan Pie", kcal: 413, type: "Cheat" },
            { name: "Chocolate Cake", kcal: 371, type: "Cheat" },
            { name: "Cheesecake", kcal: 321, type: "Cheat" },
            { name: "Hot Dog (with bun)", kcal: 290, type: "Cheat" },
            { name: "Corn Dog", kcal: 250, type: "Cheat" },
            { name: "Chicken Nuggets", kcal: 296, type: "Cheat" },
            { name: "Fried Chicken", kcal: 246, type: "Cheat" },
            { name: "Taco (Hard Shell, Beef)", kcal: 226, type: "Cheat" },
            { name: "Burrito (Bean and Cheese)", kcal: 190, type: "Cheat" },
            { name: "Nachos (with Cheese)", kcal: 306, type: "Cheat" },
            { name: "Mozzarella Sticks", kcal: 318, type: "Cheat" },
            { name: "Onion Rings", kcal: 411, type: "Cheat" },
            { name: "Tater Tots", kcal: 315, type: "Cheat" },
            { name: "Macaroni and Cheese", kcal: 164, type: "Cheat" },
            { name: "Ramen (Instant, prepared)", kcal: 436, type: "Cheat" },
            { name: "Popcorn (Movie Theater)", kcal: 583, type: "Cheat" },
            { name: "Soft Pretzel", kcal: 340, type: "Cheat" },
            { name: "Churro", kcal: 461, type: "Cheat" },
            { name: "Cotton Candy", kcal: 394, type: "Cheat" },
            { name: "Marshmallow", kcal: 318, type: "Cheat" },
            { name: "Gummy Bears", kcal: 343, type: "Cheat" },
            { name: "Jelly Beans", kcal: 375, type: "Cheat" },
            { name: "Milk Chocolate Bar", kcal: 535, type: "Cheat" },
            { name: "Peanut Butter Cups", kcal: 515, type: "Cheat" },
            { name: "Waffle (with syrup)", kcal: 291, type: "Cheat" },
            { name: "Pancakes (with syrup)", kcal: 227, type: "Cheat" },
            { name: "French Toast", kcal: 229, type: "Cheat" },
            { name: "Milkshake (Chocolate)", kcal: 112, type: "Cheat" },
            { name: "Soda (Cola)", kcal: 41, type: "Cheat" }

        ]
    },

    ui: {

        switchTab: (id, btn) => {
            document.querySelectorAll('.stage').forEach(s => s.classList.remove('active'));
            document.querySelectorAll('.tab').forEach(t => t.classList.remove('active'));
            document.getElementById(`tab-${id}`).classList.add('active');
            btn.classList.add('active');
        },

        setGender: (g, btn) => {
            Engine.state.gender = g;
            document.querySelectorAll('.choice').forEach(c => c.classList.remove('active'));
            btn.classList.add('active');
        },

        updateBars: (p, c, f) => {

            document.getElementById('p-bar').style.width = p + '%';
            document.getElementById('p-val').innerText = p + '%';

            document.getElementById('c-bar').style.width = c + '%';
            document.getElementById('c-val').innerText = c + '%';

            document.getElementById('f-bar').style.width = f + '%';
            document.getElementById('f-val').innerText = f + '%';

        }
    }

};